filer/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from django.conf.urls import url

from . import settings as filer_settings
from . import views

urlpatterns = [
    url(
        filer_settings.FILER_CANONICAL_URL + r'(?P<uploaded_at>[0-9]+)/(?P<file_id>[0-9]+)/$',  # flake8: noqa
        views.canonical,
        name='canonical'
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

from mysite.upload import upload_image

admin.site.site_header = '视频点播管理系统'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin_resumable/', include('admin_resumable.urls')),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^tv/api/', include("epg.api.urls", namespace='tv-api')),
    url(r'^vod/api/', include("vodmanagement.api.urls", namespace='vod-api')),
    url(r'^uploads/(?P<dir_name>[^/]+)$', upload_image, name='upload_image')
]
# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vodmanagement/api/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from .views import (
    VodListAPIView, HomeListAPIView, HomeOverViewAPIView,CategoryListAPIView,
    YearListAPIView, RegionListAPIView, VodDetailAPIView
)


cache_time = 10
urlpatterns = [
    url(r'^$', cache_page(cache_time)(VodListAPIView.as_view()), name='list'),
    url(r'^home/$', cache_page(cache_time)(HomeListAPIView.as_view()), name='home'),
    url(r'^home/overview$', cache_page(cache_time)(HomeOverViewAPIView.as_view()), name='home_overview'),
    url(r'^category/$', cache_page(cache_time)(CategoryListAPIView.as_view()), name='category'),
    url(r'^year/$', cache_page(cache_time)(YearListAPIView.as_view()), name='year'),
    url(r'^region/$', cache_page(cache_time)(RegionListAPIView.as_view()), name='region'),
    url(r'^(?P<id>[\w-]+)/$', cache_page(cache_time)(VodDetailAPIView.as_view()), name='detail'),
]

vodmanagement/forms.py
from django import forms

from vodmanagement.custom_widget import KindEditor
from vodmanagement.models import MultipleUpload, Restore, VideoCategory, Vod
from vodmanagement.utils import save_path_choices, get_save_path_choice, create_storage_paths


class MultipleUploadForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MultipleUploadForm, self).__init__(*args, **kwargs)
        self.fields['save_path'] = forms.ChoiceField(choices=save_path_choices(), label=self.fields['save_path'].label)

    class Meta:
        model = MultipleUpload
        fields = '__all__'


class RestoreForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RestoreForm, self).__init__(*args, **kwargs)
        self.fields['save_path'] = forms.ChoiceField(choices=save_path_choices(), label=self.fields['save_path'].label)

    class Meta:
        model = Restore
        fields = '__all__'


class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = VideoCategory
        widgets = {
            'type': forms.RadioSelect,
        }
        fields = '__all__'


class VodForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VodForm, self).__init__(*args, **kwargs)
        if self.instance.image.name and self.instance.video.name:
            self.fields['save_path'] = forms.ChoiceField(choices=get_save_path_choice(self.instance.save_path), label=self.fields['save_path'].label)
        else:
            self.fields['save_path'] = forms.ChoiceField(choices=save_path_choices(), label=self.fields['save_path'].label)
            # self.fields['save_path'].widget.attrs['disabled='disabled''] = True
        create_storage_paths()

    def clean_title(self):
        data = self.cleaned_data['title']
        return data

    def clean(self):
        return super(VodForm, self).clean()

    class Meta:
        model = Vod
        fields = (
            'category',
            'save_path',
            'video',
            'title',
            'image',
            'year',
            'description',
            'slug',
            'search_word',
        )
        widgets = {
            'description': KindEditor(),
        }

vodmanagement/api/views.py
import random
from wrapcache import wrapcache
from django.db.models import Q
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)

from .serializers import (
    VodListSerializer, VodDetailSerializer, CategoryListSerializer,
    RegionListSerializer, VodHomeListSerializer
)
from vodmanagement.models import Vod, VideoCategory, VideoRegion
from vodmanagement.views import get_years
from .pagination import VodPageNumberPagination
from .permissions import HasPermission


@wrapcache(60)
def get_all_videos(main_category):
    query_set = Vod.objects.filter(active=1)
    if main_category:
        result = query_set.filter(category__subset__name=main_category)
        result |= query_set.filter(category__name=main_category)
        return result.distinct()
    return query_set


@wrapcache(60)
def get_filter_videos(query_set, category=None, year=None, region=None):
    if category:
        query_set = query_set.filter(category__name=category)
    if year:
        query_set = query_set.filter(year=year)
    if region:
        query_set = query_set.filter(region__name=region)
    return query_set


def checked_query_param(param: str):
    return param if (param != '全部' and param != '') else None


class VodListAPIView(ListAPIView):
    """
    VodListAPIView doc
    """
    serializer_class = VodListSerializer
    permission_classes = [AllowAny]
    pagination_class = VodPageNumberPagination  # PageNumberPagination

    def get_queryset(self, *args, **kwargs):
        main_category = self.request.query_params.get('main_category')
        queryset_list = get_all_videos(main_category)
        category = checked_query_param(self.request.query_params.get('category'))
        year = checked_query_param(self.request.query_params.get('year'))
        region = checked_query_param(self.request.query_params.get('region'))
        queryset_list = get_filter_videos(queryset_list, category=category, year=year, region=region)
        search = self.request.GET.get("search")
        if search is not None and search != '':
            queryset_list = queryset_list.filter(
                Q(title__icontains=search) |
                Q(description__icontains=search)
            )
        return queryset_list


class VodDetailAPIView(RetrieveAPIView):
    """
    VodDetailAPIView doc

    """
    lookup_field = 'id'
    serializer_class = VodDetailSerializer
    permission_classes = [HasPermission]

    def get_queryset(self, *args, **kwargs):
        query_set = Vod.objects.filter(active=1)
        return query_set


@wrapcache(60)
def gen_categories():
    categories = {}
    for level_1 in VideoCategory.objects.filter(level=1):
        children = level_1.subset.all()
        categories[level_1.name] = CategoryListSerializer(children, many=True).data
    return categories


class CategoryListAPIView(APIView):
    """
    CategoryListAPIView doc
    """
    serializer_class = CategoryListSerializer
    permission_classes = [AllowAny]
    queryset = VideoCategory.objects.all()

    def get(self, request, format=None):
        return Response(gen_categories())


class YearListAPIView(APIView):
    permission_classes = [AllowAny]

    def get(self, *args, **kwargs):
        main_category = self.request.query_params.get('category')
        if main_category is None:
            Response('Error, the year list request must contain 1 first level category parameter.')
        year_list = get_years(main_category)
        return Response(year_list)


class RegionListAPIView(ListAPIView):
    permission_classes = [AllowAny]
    serializer_class = RegionListSerializer

    def get_queryset(self, *args, **kwargs):
        return VideoRegion.objects.all()


def get_random_videos(max_length=6):
    random_videos = get_all_videos(None)
    videos_length = len(random_videos)
    if videos_length <= max_length:
        return random_videos
    else:
        return random.sample(list(random_videos), max_length)


class HomeListAPIView(APIView):
    """
    HomeListAPIView doc
    """
    permission_classes = [AllowAny]

    def get(self, request, format=None):
        preview_categories = {}
        videos = get_random_videos()
        preview_categories['count'] = len(videos)
        preview_categories['videos'] = VodHomeListSerializer(videos, many=True).data
        return Response(preview_categories)


class HomeOverViewAPIView(APIView):
    """
    展示在主页的每个一级分类下最新的N个视频,分类名称通过GET请求中的category参数确定,N通过GET请求中的length参数确定
    """
    permission_classes = [AllowAny]

    def get(self, request, format=None):
        category = self.request.query_params.get('category')
        length = self.request.query_params.get('length')
        try:
            if category is not None:
                if length is None: length = 4
                videos = get_all_videos(None).filter(
                    Q(category__subset__name=category) |
                    Q(category__name=category)
                )[:int(length)]
                if not videos:
                    raise ValueError('视频列表为空,请检查分类名称')
                overview_videos = VodListSerializer(videos, many=True).data
                return Response(overview_videos)
            else:
                raise ValueError('缺少分类名称参数category')
        except Exception as e:
            return Response({
                'error': str(e)
            })

vodmanagement/views.py
# get distinct years of the Vod ,result in a list
# ['2014','20323',...]
from vodmanagement.models import Vod
from vodmanagement.utils import get_vod_field_list


def get_years(category):
    category = None if category == '全部' or category == '' else category
    _years = get_vod_field_list(Vod, 'year', category)
    years = []
    for year in _years:
        years.append(year[0])
    return years

templates/vodmanagement/basic.html
<!DOCTYPE html>
{% load i18n staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Blank Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    {#  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">#}
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- jQuery 3.1.1 -->
    <script src="{% static 'plugins/jQuery/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <!-- <script src="../../plugins/fastclick/fastclick.js"></script> -->
    <!-- AdminLTE App -->
{#    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>#}
{#    <script src="{% static 'js/video.js' %}"></script>#}
    <script src="{% static 'plugins/hola/videojs.hls.js' %}"></script>
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/video-js.css' %}">#}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/hola/video-js.css' %}">
    <!-- AdminLTE for demo purposes -->
    <!-- <script src="../../dist/js/demo.js"></script> -->
    {% block scripts %}

    {% endblock scripts %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>

{#  <script src="{% static 'js/html5shiv.js' %}"></script>#}
{#  <script src="{% static 'js/respond.min.js' %}"></script>#}
  <![endif]-->
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <!--<a href="{% url 'vod:homepage' %}" class="logo">
      <span class="logo-mini"><b>A</b>LT</span>
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    -->
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <div class="nav navbar-nav">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
            <div class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Year<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% for year in years %}
                            <li onclick="click_year(this)"><a href="#">{{ year }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </div>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->

                    <!-- Notifications: style can be found in dropdown.less -->

                    <!-- Tasks: style can be found in dropdown.less -->

                    <li>
                        <a href="/">{% trans "Home" %}</a>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ user }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle"
                                     alt="User Image">
                                <p>
                                    {{ user }} - Web Developer
                                    <small>Member since Nov. 2012</small>
                                </p>
                            </li>
                            <!-- Menu Body -->

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'admin:index' %}" class="btn btn-default btn-flat">Settings</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'vod:logout' %}" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                </ul>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{ user }}</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->

            {% block search_field %}
                <!--search start-->
                <form action="/list/" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="search_word" class="form-control" placeholder="Search..."/>
                        <span class="input-group-btn"><button type="submit" name="search" id="search-btn"
                                                              class="btn btn-flat"><i class="fa fa-search"></i></button></span>
                        <input id="search-year" type="text" name="year" class="form-control" style="display: none;"/>
                    </div>
                </form>
                <!--search end-->
            {% endblock %}


            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header" id="all_video"><a href="{% url 'vod:list' %}"><i class="fa fa-home"></i> <span>All Videos</span></a>
                </li>

                {% block category_list %}
                    {% for item in categorys %}
                        {% if item.name == title %}
                            <li class="active" id="video_{{ item.name }}">
                                {% else %}
                            <li class="" id="video_{{ item.name }}">
                        {% endif %}

                    <a href="{% url 'vod:list-detail' item.name %}">
                        <i class="fa fa-book"></i> <span>{{ item.name }}</span>
                    </a>
                    <!--<ul class="treeview-menu">
                        <li><a href=""><i class="fa fa-circle-o"></i>Hello</a></li>
                    </ul>-->
                    </li>
                    {% endfor %}
                {% endblock %}

                <!-- <li><a href="{% url 'vod:login' %}"><i class="fa fa-sign-in"></i> <span>Login Page</span></a></li> -->
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" >
        <!-- Content Header (Page header) -->
        {% block content-header %}
            <section class="content-header">
                <h1>
                    Blank page
                    <small>it all starts here</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li><a href="#">Examples</a></li>
                    <li class="active">Blank page</li>
                </ol>
            </section>
        {% endblock %}

        <!-- Main content -->
        <section class="content">
            <div class="col-md-12">
                <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" style="display: none;">
                    开始演示模态框
                </button>
                <!-- 模态框（Modal） -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title" id="myModalLabel">
                                    模态框（Modal）标题
                                </h4>
                            </div>
                            <div class="modal-body">
                                <form action="/list/" method="get" class="sidebar-form">
                                    <div class="input-group">
                                        <input type="text" name="search_word" class="form-control"
                                               placeholder="Search..."/>
                                        <span class="input-group-btn"><button type="submit" name="search"
                                                                              id="search-btn" class="btn btn-flat"><i
                                                class="fa fa-search"></i></button></span>
                                        <input id="search-year" type="text" name="year" class="form-control"
                                               style="display: none;"/>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                                </button>
                                <button type="button" class="btn btn-primary">
                                    提交更改
                                </button>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal -->
                </div>
            </div>
            {% block content %}
            {% endblock %}

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

</div>

<script>
    $(document).ready(function () {
        //$('.sidebar-menu').tree()
    })
</script>
{% block own_scrips %}
{% endblock %}
<script src="{% static 'js/app.js' %}"></script>
</body>
</html>

<!--hhy============================================== -->

templates/vodmanagement/change_form.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script src="{% static 'plugins/jQuery/jquery-3.1.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'font-awesome-4.7/css/font-awesome.min.css' %}">
    <script type="text/javascript" src="{% static 'plugins/jquery-confirm/jquery-confirm.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/jquery-confirm/jquery-confirm.min.css' %}">
    <script type="text/javascript" src="{% static 'plugins/isLoading.min.js' %}"></script>
{% endblock %}

{% block content %}
    {% block content_info %}
        <h1 style="color: red;">
            为保证点播节目播放的兼容性，视频文件尽量上传<b>视频编码为H.264</b>,<b>音频编码为AAC</b>的<b>.mp4</b>格式<br/>
            如果视频文件不是<b>.mp4</b>格式，请在点播节目列表处进行手动格式转换。
        </h1>
    {% endblock %}
    {{ block.super }}
{% endblock %}

{# If I add below, the many to many field will not save correctly#}
{#{% block admin_change_form_document_ready %}#}
{#    {{ block.super }}#}
{#    <script>#}
{#        $("[name='_save']").click(function (e) {#}
{#            e.preventDefault();#}
{#            console.log("click save");#}
{#            if($('form').hasClass('uploading')){#}
{#                console.log('upload is not complete');#}
{#            } else {#}
{#                $("form").submit();#}
{#            }#}
{#        });#}
{#    </script>#}
{#{% endblock %}#}

templates/vodmanagement/detail.html
{% extends "vodmanagement/basic.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block own_scrips %}
    {#    <script src="{% static 'js/hola_player.js'%}"></script>#}
    {#    <script>#}
    {#        window.hola_player()#}
    {#    </script>#}
    <!-- <script type="text/javascript">
        $(document).ready(function(){
            $("#all_video").addClass("active")
        })
    </script> -->
{% endblock %}

{% block search_field %}
    <!--search start-->
    <form action="/list/" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="search_word" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
        </button>
      </span>
        </div>
    </form>
    <!--search end-->
{% endblock %}

{% block content-header %}
    <section class="content-header">
        <h1>
            {{ video.title }}
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="/list/{{ video.category }}">{{ video.category }}</a></li>
            <li class="active">{{ video.title }} </li>
        </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- <div class="page-heading">
    {{video.title}}
</div> -->
    <div class="jumbotron" style="background: transparent;">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body" style="height: 500px;">
                            <video id="video{{ video.pk }}" class='video-js vjs-default-skin'
                                   style="width: 100%;height: 100%"
                                   controls
                            data-setup='{"plugins":{"hola_skin":{"css":false}}}'>
                                <!-- preload="auto" -->
                                <source src="{{ video.video.url }}" type="video/mp4">
                            </video>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 col-xs-12 col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading text-center">
                            <h4 style="display: inline">Description</h4>
                            <span class="pull-right" style="color: #666">{{ video.view_count }} views</span>
                        </div>
                        <div class="panel-body">
                            <span>{{ video.description }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{#    <style>#}
{#        #instructions {#}
{#            max-width: 640px;#}
{#            text-align: left;#}
{#            margin: 30px auto;#}
{#        }#}
{##}
{#        #instructions textarea {#}
{#            width: 100%;#}
{#            height: 100px;#}
{#        }#}
{##}
{#        /* Show the controls (hidden at the start by default) */#}
{#        .video-js .vjs-control-bar {#}
{#            display: -webkit-box;#}
{#            display: -webkit-flex;#}
{#            display: -ms-flexbox;#}
{#            display: flex;#}
{#        }#}
{##}
{#        /* Make the demo a little prettier */#}
{#        body {#}
{#            margin-top: 20px;#}
{#            background: #222;#}
{#            text-align: center;#}
{#            color: #aaa;#}
{#            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;#}
{#            background: radial-gradient(#333, hsl(200, 30%, 6%));#}
{#        }#}
{##}
{#        a, a:hover, a:visited {#}
{#            color: #76DAFF;#}
{#        }#}
{#    </style>#}
{% endblock %}

templates/vodmanagement/each_video.html
{% load staticfiles %}
{% load thumbnail %}

<div class="panel panel-default " style="border: 0px">  
    <a href='{{ video.get_absolute_url }}'>
        <img src="{{ video.image|thumbnail_url:'avatar' }}" width="100%"
             height="auto"/>
        <span class="video-resolution-text">{{ video.definition }}</span>
        <div class="panel-heading">
        <li class="title">{{ video.title }}</li>
        
        <li class="duration">
        DUR:{{ video.duration }}
        </li>
        </div>
    </a>
</div>

templates/vodmanagement/listlink.html
{% extends "vodmanagement/basic.html" %}
{% load static %}
{% block content %}
<div class="container">
   <div class="row">
{% for link in links %}
    {# Each "contact" is a Contact model object. #}
   <div class="col-xs-6">
       <div class="panel panel-primary">
            <div class="panel-heading">
                <h3>{{ link.name }}</h3>
            </div>
            <div class="panel-body">
                {{ link.url|safe}}
            </div>
       </div>
    </div>
{% endfor %}
   </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if videos.has_previous %}
            <a href="?page={{ videos.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ videos.number }} of {{ videos.paginator.num_pages }}.
        </span>

        {% if videos.has_next %}
            <a href="?page={{ videos.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/vodmanagement/upload.html
{% extends "vodmanagement/basic.html" %}
{% load static %}
{% block content %}
<script src="{% static 'ajaxuploader/js/fileuploader.js' %}"></script>
<script src="{% static 'file_form/file_form.js' %}"></script>
<link rel="stylesheet" href="{% static 'ajaxuploader/css/fileuploader.css'%}">

<form id="example-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
</form>

<script>
   $(function() {
       initUploadFields($('#example-form'));
   });
</script>

{% endblock %}