admin_resumable/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^admin_resumable/$', views.admin_resumable, name='admin_resumable'),
    url(r'^admin_resumable_restore/$', views.admin_resumable_restore, name='admin_resumable_restore'),
    url(r'^admin_resumable_set/$', views.admin_resumable_set, name='admin_resumable_set'),
    url(r'^admin_resumable_delete/$', views.admin_resumable_delete, name='admin_resumable_delete'),
]

filer/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from django.conf.urls import url

from . import settings as filer_settings
from . import views

urlpatterns = [
    url(
        filer_settings.FILER_CANONICAL_URL + r'(?P<uploaded_at>[0-9]+)/(?P<file_id>[0-9]+)/$',  # flake8: noqa
        views.canonical,
        name='canonical'
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

from mysite.upload import upload_image

admin.site.site_header = '视频点播管理系统'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin_resumable/', include('admin_resumable.urls')),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^tv/api/', include("epg.api.urls", namespace='tv-api')),
    url(r'^vod/api/', include("vodmanagement.api.urls", namespace='vod-api')),
    url(r'^uploads/(?P<dir_name>[^/]+)$', upload_image, name='upload_image')
]
# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

epg/models.py
from django.db import models


class Channel(models.Model):
    channel_id = models.CharField(max_length=50, unique=True)
    channel_name = models.CharField(max_length=50, null=True, blank=True)
    rtmp_url = models.CharField(max_length=100, null=True, blank=True)
    active = models.IntegerField(null=True, blank=True)
    start = models.IntegerField(null=True, blank=True)
    PID = models.IntegerField(null=True, blank=True)
    PGID = models.IntegerField(null=True, blank=True)
    client_ip = models.CharField(max_length=50, null=True, blank=True)
    sort = models.IntegerField(null=False, blank=True, default=0)

    class Meta:
        managed = False
        db_table = 'channel'
        verbose_name = '频道'
        verbose_name_plural = '频道管理'

    def __str__(self):
        return self.channel_name + '(' + self.channel_id + ')'


class Program(models.Model):
    channel = models.ForeignKey(Channel, to_field='channel_id', null=True)
    start_time = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    end_time = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    url = models.CharField(max_length=50, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    finished = models.IntegerField(null=True, blank=True, default=0)
    event_id = models.IntegerField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'program'
        verbose_name = '节目'
        verbose_name_plural = '节目管理'

    def __str__(self):
        return str(self.channel) + ':' + self.title

vodmanagement/models.py
import logging
import os
import datetime
import six
import humanfriendly
from pathlib import Path
from django.db import models
from django.utils.html import format_html
from django.utils.encoding import uri_to_iri
from django.core.management import call_command
from django.utils.safestring import mark_safe
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_init, post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
from django.core.files import File
from sortedm2m.fields import SortedManyToManyField
from uuslug import uuslug
# from moviepy.editor import VideoFileClip # get video duration
from .my_storage import VodStorage
from admin_resumable.fields import (
    ModelAdminResumableFileField, ModelAdminResumableImageField,
    ModelAdminResumableMultiFileField, ModelAdminResumableRestoreFileField
)
from xpinyin import Pinyin  # for pinyin search

if six.PY3:
    from django.utils.encoding import smart_str
else:
    from django.utils.encoding import smart_unicode as smart_str
"""
Copy data in XXX model:
>>> 
from vodmanagement.models import *
objs=Vod.objects.all()
for i in range(0,10):
    newobj=objs[0]
    newobj.pk=None
    newobj.save()    
>>>
This script will copy 10 objs[0] in database
"""


class UserPermission(models.Model):
    user = models.OneToOneField(User)
    permission = models.CharField(max_length=100, blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def has_permision(self):
        delta = self.end_date.date() - datetime.date.today()
        print(delta.days)
        if delta.days >= 0:
            return True
        return False


class VodManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(VodManager, self)  # .filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    VodModel = instance.__class__
    print('save')
    if VodModel.objects.count() is not 0:
        new_id = VodModel.objects.order_by("id").last().id - 1
    else:
        new_id = 0
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    print('save image')
    return "%s/%s" % (new_id, filename)


def upload_image_location(instance, filename):
    VodModel = instance.__class__
    if VodModel.objects.count() is not 0:
        new_id = VodModel.objects.order_by("id").last().id + 1
    else:
        new_id = 0
    folder = instance.save_path
    if folder == "default":
        category = instance.category.name
    else:
        category = instance.category.name + '_' + folder
    return "%s/images/%s/%s" % (category, new_id, filename)


def upload_record_image_location(instance, filename):
    return "%s/images/%s" % (settings.RECORD_MEDIA_FOLDER, filename)


def default_description(instance):
    default = instance.title
    print(default)
    return 'The %s description' % default


# Create your models here.
def default_filedir():
    return settings.MEDIA_ROOT


# ---------------------------------------------------------------------
# if leave path blank,it will save it as the default file dir:settings.MEDIA_ROOT
class FileDirectory(models.Model):
    path = models.CharField(max_length=512, default=default_filedir, blank=True)

    class Meta:
        verbose_name = '视频上传路径'
        verbose_name_plural = '视频上传路径管理'

    def __str__(self):
        return self.path

    def save(self, *args, **kwargs):
        if self.path is None or self.path == "":
            self.path = default_filedir()
        super(FileDirectory, self).save(*args, **kwargs)


# ---------------------------------------------------------------------
# Two selections only:Common,Special purpose
TYPES = (
    ('common', 'Common'),
    ('special', 'Special purpose'),
)
VIDEO_QUALITY = [
    ('SD', '标清'),
    ('HD', '高清'),
    ('FHD', '超清'),
]
SAVE_PATH = (
    ('', settings.LOCAL_MEDIA_ROOT),
)


class VideoRegion(models.Model):
    name = models.CharField(max_length=200, verbose_name='地区', unique=True)

    class Meta:
        verbose_name = '视频地区管理'
        verbose_name_plural = '视频地区'

    def __str__(self):
        return self.name


class VideoCategory(models.Model):
    name = models.CharField(max_length=128, verbose_name='分类名称')
    type = models.CharField(max_length=128, choices=TYPES, default='common', verbose_name='类型')
    isSecret = models.BooleanField(default=False, verbose_name='是否加密')
    level = models.IntegerField(null=False, blank=False, default=1, choices=((1, '一级分类'), (2, '二级分类')),
                                verbose_name='分类等级')
    subset = models.ManyToManyField('self', blank=True, verbose_name='分类关系')

    class Meta:
        verbose_name = '视频分类'
        verbose_name_plural = '视频分类管理'

    def __str__(self):
        base_name = self.name + str('  (level %d)' % (self.level))
        if self.subset.first() and self.level == 2:
            return '--'.join([self.subset.first().name, base_name])
        else:
            return base_name

    def save(self, *args, **kwargs):
        super(VideoCategory, self).save(*args, **kwargs)

    def colored_level(self):
        color_code = 'red' if self.level == 1 else 'green'
        return format_html(
            '<span style="color:{};">{}</span>',
            color_code,
            self.get_level_display()
        )

    colored_level.short_description = '分级'


# ---------------------------------------------------------------------
class MultipleUpload(models.Model):
    files = ModelAdminResumableMultiFileField(null=True, blank=True, storage=VodStorage(), verbose_name='文件')
    save_path = models.CharField(max_length=128, blank=False, null=True, verbose_name='保存路径')
    category = models.ForeignKey(VideoCategory, null=True, verbose_name='分类')

    class Meta:
        verbose_name = '批量上传'
        verbose_name_plural = '批量上传管理'


# ---------------------------------------------------------------------
# TODO(hhy): Please Leave This Model Here. It Will Be Use In The Future.
# class VideoTag(models.Model):
#     name = models.CharField(max_length=200, null=False, blank=False)
#
#     def __str__(self):
#         return self.name


class Restore(models.Model):
    txt_file = models.FileField(blank=True, null=True, verbose_name='备份配置文件')
    zip_file = ModelAdminResumableRestoreFileField(null=True, blank=True, storage=VodStorage(), verbose_name='压缩包')
    save_path = models.CharField(max_length=128, blank=False, null=True)  # ,default=FileDirectory.objects.first())

    class Meta:
        verbose_name = '视频导入'
        verbose_name_plural = '视频导入'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        result = super(Restore, self).save()
        file_path = self.txt_file.path
        call_command('loaddata', file_path)
        return result


class Vod(models.Model):
    title = models.CharField(max_length=120, verbose_name='标题')
    # image = models.ImageField(upload_to=upload_image_location, null=True, blank=True)
    # video = models.FileField(null=True,blank=True,storage=VodStorage())
    image = ModelAdminResumableImageField(null=True, blank=True, storage=VodStorage(), max_length=1000,
                                          verbose_name='缩略图')
    video = ModelAdminResumableFileField(null=True, blank=True, storage=VodStorage(), max_length=1000,
                                         verbose_name='视频')
    duration = models.CharField(max_length=50, blank=True, null=True, verbose_name='时长')
    local_video = models.FilePathField(path=settings.LOCAL_MEDIA_ROOT, blank=True, recursive=True)
    definition = models.CharField(max_length=10, choices=VIDEO_QUALITY, blank=False, default='H', verbose_name='清晰度')
    category = models.ForeignKey(VideoCategory, null=True, blank=True, verbose_name='分类')
    save_path = models.CharField(max_length=128, blank=False, null=True, default='default', verbose_name='保存路径')  # ,default=FileDirectory.objects.first())
    year = models.CharField(max_length=10, blank=False, null=True, default=datetime.datetime.now().year, verbose_name='年份')
    region = models.ForeignKey(VideoRegion, to_field='name', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='地区')
    file_size = models.CharField(max_length=128, default='0B', editable=False, verbose_name='文件大小')
    view_count = models.IntegerField(default=0, verbose_name='观看次数')
    view_count_temp = 0
    creator = models.ForeignKey(User, null=True, blank=False, editable=False)
    description = models.TextField(blank=True, verbose_name='简介')
    select_name = models.CharField(max_length=100, blank=False, verbose_name='选集名称', default='1')
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='创建时间')  # The first time added
    slug = models.SlugField(unique=True, blank=True)
    search_word = models.CharField(max_length=10000, null=True, blank=True)
    # tags = models.ManyToManyField(VideoTag, blank=True)
    video_list = SortedManyToManyField('self', blank=True)
    # video_list = models.ManyToManyField('self', blank=True, symmetrical=False)
    active = models.IntegerField(null=True, blank=False, default=0, choices=((1, 'Yes'), (0, 'No')))
    progress = models.IntegerField(null=True, blank=True, default=0)
    objects = VodManager()

    class Meta:
        verbose_name = '视频'

admin_resumable/templates/admin_resumable/file_input.html
<script>
    {% block script_head %}{% endblock %}

    function getFileName(file) {
        var pos = file.lastIndexOf(".");
        return file.substring(0, pos);
    }

    function getFileType(file) {
        var pos = file.lastIndexOf(".");
        return file.substring(pos + 1);
    }


    (function ($) {
        $(function () {
            var file_names = '';
            var save_path_sel = $('#id_save_path');
            var confirm_sel = $('#confirm_upload');
            var save_path = save_path_sel.val();
            var cur_option = save_path_sel.find('[value=' + save_path + ']').text();
            var video_allow = ['mp4', 'm3u8'];
            var $process_bar = $('#{{ id }}_progress');
            $('form').submit(function () {
                if ($(this).hasClass('{{ name }}_disabled')) {
                    return false;
                }
            });
            if (!(new Resumable().support)) {
                alert("No uploader support");
            }
            var r = new Resumable({
                target: '{% url 'admin_resumable' %}',
                chunkSize: {{ chunkSize }},
                query: {
                    csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
                    field_name: '{{ field_name }}',
                    content_type_id: '{{ content_type_id }}'
                },
            });
            r.assignBrowse($('#{{ id }}_input_file'));
            r.assignDrop($('#{{ id }}_input_file'));
            r.on('fileAdded', function (file, event) {
                {% block vod_title %}{% endblock %}
                console.log("add file");
                reset_processbar();
                {#                file_names += file.fileName + '<br/>';#}
            });
            r.on('fileSuccess', function (file, message) {
                $('#{{ id }}').val(message);
                var before = $("#{{ id }}_uploaded_status").html();
                $("#{{ id }}_uploaded_status").html(before + '<br/>' + message + ' 上传成功');

                {#                if (video_allow.toString().indexOf(getFileType(file.fileName)) > -1) {#}
                $("form").removeClass('uploading');
                {#                }#}
                {#            $("[name='_save'").click();#}
                {# $('#{{ id }}_upload_icon').hide();#}
                r.removeFile(file);
                console.log("upload done");
                success_processbar();
                {% block file_success %}

                {% endblock %}
            });
            r.on('fileError', function (file, message) {
                $("#{{ id }}_uploaded_status").html(message);
            });
            r.on('progress', function (file, message) {
                {#                $('#{{ id }}_progress').val(r.progress());#}
                update_processbar(r.progress(true));
                $('#{{ id }}_upload_icon').show();

            });

            $('#{{ id }}_input_file').on('change', function (e) {
                console.log('change');
                setTimeout(function () {
                    file_names = '';
                    r.files.map(function (file) {
                        file_names += file.fileName + '<br/>';
                    });
                    var msg = '<div class="text-center" style="color:green;font-weight:bold">确定要上传以下文件:</div><b>'
                        + file_names
                        + "</b>"
                        + '<div class="text-center" style="color:green;font-weight:bold">到:</div>'
                        + '<span style="color: red;font-weight:bold">'
                        + cur_option
                        + '</span>';
                    msg = '<div class="text-center">' + msg + '</div>';
                    console.log(msg);
                    jQuery.confirm({
                        columnClass: 'medium',
                        icon: 'fa fa-warning',
                        title: '确认',
                        content: msg,
                        type: 'green',
                        buttons: {
                            ok: {
                                text: "是！",
                                btnClass: 'btn-primary',
                                keys: ['enter'],
                                action: function () {
                                    console.log("upload start");
                                    var category = $("#id_category").val();
                                    r.opts.query = Object.assign(r.opts.query, {
                                        'category': category,
                                        'save_path': save_path
                                    });
                                    var file_name_list = [];
                                    r.files.map(function (file) {
                                        file_name_list.push(file.fileName);
                                    });
                                    console.log(file_name_list);
                                    var content = {
                                        'upload_to_': save_path,
                                        field_name: '{{ field_name }}',
                                        content_type_id: '{{ content_type_id }}',
                                        'file_names': JSON.stringify(file_name_list)
                                    };
                                    $.get('{% url 'admin_resumable_set' %}', content, function (data, status) {
                                        console.log(data);
                                        console.log(status);
                                        if (data.startsWith('[')) {
                                            var error_files = JSON.parse(data);
                                            var error_message = '文件<br/><br/><span style="color: red;font-weight:bold">';
                                            error_files.map(function (file) {
                                                error_message += file + '<br/>';
                                            });
                                            error_message += '</span><br/>已经存在!';
                                            error_message = '<div class="text-center">' + error_message + '</div>';
                                            // Confirm to delete the existing file.
                                            jQuery.confirm({
                                                columnClass: 'medium',
                                                icon: 'fa fa-warning',
                                                title: '是否删除服务器文件',
                                                content: error_message,
                                                type: 'red',
                                                buttons: {
                                                    ok: {
                                                        text: "是！",
                                                        btnClass: 'btn-primary',
                                                        keys: ['enter'],
                                                        action: function () {
                                                            console.log('start delete file');
                                                            $.get('{% url 'admin_resumable_delete' %}', {'delete_file_names': data, 'save_path': save_path}, function (data, status) {
                                                                r.upload();
                                                                $("form").addClass('uploading')
                                                            });
                                                        }
                                                    },
                                                    cancel: {
                                                        text: "否",
                                                        action: function () {
                                                            console.log('cancel delete file');
                                                            r.cancel();
                                                            file_names = '';
                                                            console.log('Canncel upload because of file already exists.');
                                                        }
                                                    }
                                                }
                                            });


                                        } else {
                                            r.upload();
                                            $("form").addClass('uploading')
                                        }
                                    });
                                }
                            },
                            cancel: {
                                text: "否",
                                action: function () {
                                    console.log("refuse upload");
                                    r.cancel();
                                    file_names = '';
                                }
                            }
                        }
                    })
                }, 500)
            });
            function update_processbar(value) {
                var now = value * 100;
                if (now > 95) {
                    $process_bar.addClass('progress-bar-warning');
                    $process_bar.find("span").html("处理中...");
                } else {
                    $process_bar.removeClass('progress-bar-success');

                }
                $process_bar.css('width', now + '%');

            }

            function success_processbar() {
                $process_bar.removeClass('progress-bar-warning');
                $process_bar.addClass('progress-bar-success');
                $process_bar.find("span").html("上传成功");
            }

            function reset_processbar() {
                $process_bar.removeClass('progress-bar-success');
                $process_bar.find("span").html("上传中...");
            }
        });

        function reset_processbar(bar){
            bar.removeClass('progress-bar-success');
            bar.find("span").html("上传中...");
        }

    })(jQuery);
    {#    })(jQuery);#}


</script>
<div id="container">
    {#    <p id="{{ id }}_file_upload">#}
    <p class="file-upload">
        {% if value %}
            Currently:
            {% if file_url %}
                <a id="{{ id }}_link" target="_new" href="{{ file_url }}">{{ file_url }}</a>
                {% if show_thumb %}
                    <img src="{{ file_url }}" style="width:250px;">
                {% endif %}
            {% else %}
                {{ value }}
            {% endif %}
            {{ clear_checkbox }}
            <br>
            Change:
        {% endif %}

        <span id="{{ id }}_uploaded_status"></span>
        <input type="file" id="{{ id }}_input_file" style="position：absolute;">
    </p>
    {#    <progress id="{{ id }}_progress" value="0" max="1" style="width:500px"></progress>#}
    <div class="progress">
        <div id="{{ id }}_progress" class="progress-bar progress-bar-striped active" role="progressbar"
             aria-valuemin="0" aria-valuemax="1">
            {#            <span class="sr-only"></span>#}
            <span id="{{ id }}_upload_icon"><i class='fa fa-circle-o-notch fa-spin'></i>上传中...</span>
        </div>
    </div>
</div>

<input type="hidden" name="{{ name }}" id="{{ id }}" value="{{ value }}">

admin_resumable/templates/admin_resumable/file_input_with_title.html
{% extends 'admin_resumable/file_input.html' %}
{% block script_head %}
    {#    function getFileName(file){#}
    {#    var pos=file.lastIndexOf(".");#}
    {#    return file.substring(0, pos);#}
    {#    }#}
{% endblock %}

{% block vod_title %}
    var filename = getFileName(file.fileName);
    $('#id_title').val(filename);
{% endblock %}

{% block file_success %}
    $.confirm({
        title: '是否自动保存?',
        content: '上传完成, 将在5秒后自动保存!',
        autoClose: 'Save|5000',
            buttons: {
            Save: {
            text: '保存',
            action: function () {
            $("[name='_save']").click();
            }
            },
            cancel: {
                text: '取消',
                action: function () {
                    $.alert('已取消自动保存,请在编辑完成后手动点击保存按钮!');
                }
            }
        }
    });
{% endblock %}